config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  concern :likable do
    member do
      post :like_up
      post :like_down
      post :like_cancel
    end
  end

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  resources :questions, concerns: :likable do
    resources :comments, only: :create, defaults: { commentable: 'questions' }
    resources :answers, concerns: :likable, shallow: true do #only: [:new, :create, :destroy]
      resources :comments, only: :create, defaults: { commentable: 'answers' }
      member do
        patch 'mark_best'
      end
    end
    resources :subscriptions, only: [:create, :destroy], shallow:  true
  end

  namespace :api do
    namespace :v1 do
      resource :profiles do
        get :me, on: :collection
        get :users, on: :collection
      end
      resources :questions, only: [:index, :show, :create]
      resources :answers, only: [:index, :show, :create]
    end
  end

  get "oauth/new_email_for_oauth", as: 'new_email_for_oauth'
  post "oauth/save_email_for_oauth", as: 'save_email_for_oauth'

  get 'search', to: 'search#index'

  root to: "questions#index"
  resources :attachments, only: :destroy

end

app/models/question.rb
class Question < ActiveRecord::Base
  include Likable
  include Commentable

  after_create :subscribe_author

  has_many :answers, dependent: :destroy
  has_many :attachments, as: :attachmentable, dependent: :destroy
  belongs_to :user
  has_many :subscriptions, dependent: :destroy 

  validates :title, :body, :user_id, presence: true

  accepts_nested_attributes_for :attachments, reject_if: :all_blank, allow_destroy: true

  private

  def subscribe_author
    self.subscriptions.create(user: user)
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  before_action :load_question, only: :show
  before_action :current_ability, only: :create

  authorize_resource

  def index
    @questions = Question.all
    respond_with @questions, each_serializer: QuestionCollectionSerializer
  end

  def show
    respond_with @question
  end

  def create
    respond_with(@question = current_resource_owner.questions.create(question_params))
  end

  private

  def load_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  include Liked

  before_action :authenticate_user!, except: [:index, :show]
  before_action :load_question, only: [:show, :edit, :update, :destroy]
  before_action :build_answer, only: :show
  after_action :publish_question, only: :create

  respond_to :html
  respond_to :js, only: [:update]

  authorize_resource

  def index
    # authorize! :read, Question
    respond_with(@questions = Question.all)
  end

  def show
    # authorize! :read, @question
    respond_with @question
  end

  def new
    # authorize! :create, Question
    respond_with(@question = current_user.questions.new)
  end

  def edit
    # authorize! :update, @question
  end

  def create
    # authorize! :create, Question
    respond_with(@question = current_user.questions.create(question_params))
  end

  def update
    # authorize! :update, Question
    @question.update(question_params)
    respond_with @question
  end

  def destroy
    # authorize! :destroy, @question
    respond_with(@question.destroy)
  end

  private

  def build_answer
    @answer = @question.answers.build
  end

  def publish_question
    PrivatePub.publish_to('/questions', question: @question.to_json) if @question.valid?
  end

  def load_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body, attachments_attributes: [:file, :id, :_destroy, :attachmentable_id, :attachmentable_type])
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_answers.html.slim
- @question.answers.each do |answer|
  div id="answer-#{ answer.id }"
    - if answer.persisted?
      - cache answer do
        p = answer.body
      = render partial: 'likes/like', locals: { likable: answer}
      p Attachments:
      ul
        - answer.attachments.each do |a|
          div id="attach-#{a.id}"
            li= link_to a.file.identifier, a.file.url
            - if can?(:destroy, @attachment)
              = link_to "Delete file", attachment_path(a), method: :delete, remote: true, id: "delete_attachment_#{a.id}"

      - if answer.best
        h1 'BEST ANSWER'
      - if can?(:mark_best, Answer)
        = link_to 'Mark as best answer', mark_best_answer_path(answer), method: :patch, remote: true
      - if can?(:update, answer) && can?(:destroy, answer)
        p = link_to 'Delete answer', answer_path(answer), method: :delete, remote: true
        p = link_to 'Edit', '', class: 'edit-answer-link', data: { answer_id: answer.id }
        p = form_for answer, remote: true, html: { id: "edit-answer-#{answer.id}" } do |f|
          = f.label :body, "Answer"
          = f.text_area :body
          = f.submit 'Save'
      
      .comments
        - answer.comments.each do |comment|
          - if comment.persisted?
            p = comment.body
      - if can?(:create, Comment)
        .comments-errors
        p = link_to 'Add comment', '', class: 'new-comment-link'
        p = form_for [answer, Comment.new] , remote: true, html: { id: "new-comment"} do |f|
          = f.label :body, 'comment body'
          = f.text_area :body, id: 'body-for-new-comment'
          = f.submit 'Create comment'      

app/views/questions/_question.html.slim
div id="question-#{ @question.id }"
  - cache [ 'question_form', @question ] do
    h1 = @question.title
    p = @question.body
  = render partial: 'likes/like', locals: { likable: @question}

  p Attachments:
  ul
    - @question.attachments.each do |a|
      div id="attach-#{a.id}"
        li= link_to a.file.identifier, a.file.url
        - if can?(:destroy, Attachment)
          = link_to "Delete file", attachment_path(a), method: :delete, remote: true, id: "delete_attachment_#{a.id}"

  - if can?(:update, @question) && can?(:destroy, @question)
    = link_to 'Delete question', question_path(@question), method: :delete
    p = link_to 'Edit', '', class: 'edit-question-link', data: { question_id: @question.id }
    p = form_for @question, remote: true, html: { id: "edit-question-#{@question.id}" } do |f|
      = f.label :title, "Question title"
      = f.text_area :title
      = f.label :body, "Question body"
      = f.text_area :body
      - @question.attachments.each do |a|
        ul
          div id="attach-#{a.id}"
            li = link_to a.file.identifier, a.file.url
      = f.submit 'Update question'
      
  .comments
    - @question.comments.each do |comment|
      - if comment.persisted?
        - cache [ 'question_form', comment ] do
          p = comment.body
  - if can?(:create, Comment)
    .comments-errors
    p = link_to 'Add comment', '', class: 'new-comment-link'
    p = form_for [@question, Comment.new] , remote: true, html: { id: "new-comment"} do |f|
      = f.label :body, 'comment body'
      = f.text_area :body, id: 'body-for-new-comment'
      = f.submit 'Create comment'

  - if user_signed_in?
    .subscription
      -if current_user.subscribed_to?(@question)
        = link_to 'Unsubscribe', subscription_path(@question.subscriptions.find_by(user_id: current_user.id)), method: :delete, remote: true, class: 'cancel_subscribe'
      - else
        = link_to 'Subscribe', question_subscriptions_path(@question), method: :post, remote: true, class: 'create_subscribe'

app/views/questions/index.html.slim
= link_to 'Sign in ', new_user_session_path
= link_to 'Sign up ', new_user_registration_path
= link_to 'Sign out ', destroy_user_session_path, method: :delete
- if can?(:create, Question)
  p = link_to 'Ask question', new_question_path
- cache collection_cache_key_for :question do
  h2 All questions here
  .questions
    - @questions.each do |question|
      div id="question-#{ question.id }"
        h2 = link_to question.title, question

= subscribe_to "/questions"
  

app/views/questions/new.html.slim
= link_to 'Sign in ', new_user_session_path
= link_to 'Sign up ', new_user_registration_path
= link_to 'Sign out ', destroy_user_session_path, method: :delete
p = link_to 'All questions', questions_path

= form_for @question do |f|
  p 
    = f.label :title
    = f.text_field :title
  p
    = f.label :body
    = f.text_area :body
  p Attachments:
  p
    = f.fields_for :attachments, @question.attachments.build do |attachment|
      = render 'attachments/attachment_fields', f: attachment
    .links
      = link_to_add_association 'add file', f, :attachments, partial: 'attachments/attachment_fields'
  = f.submit 'Create'

app/views/questions/show.html.slim
= link_to 'Sign in ', new_user_session_path
= link_to 'Sign up ', new_user_registration_path
= link_to 'Sign out ', destroy_user_session_path, method: :delete
p = link_to 'All questions', questions_path

- cache @question do
  .question data={ question_id: "#{@question.id}"}
    = render 'question'

  h1 All answers for this questions
  .answers data={ question_id: "#{@question.id}"}
    = render 'answers' 

- if can?(:create, Answer)
  = form_for [ @question, @answer ], remote: true do |f|
    = f.label :body, "You can answer"
    .answer-errors
    = f.text_area :body, id: 'body-for-new-answer'
    p
      = f.fields_for :attachments, @answer.attachments.build do |attachment|
        = render 'attachments/attachment_fields', f: attachment
      .links
        = link_to_add_association 'add file', f, :attachments, partial: 'attachments/attachment_fields'
    = f.submit 'Create answer'

= subscribe_to "/questions/#{@question.id}/answers"
= subscribe_to "/comments"

app/views/questions/update.js.erb
<% if @question.errors.present? %>
  <% @question.errors.full_messages.each do |message| %>
    $('.question-errors').html('<%= j message %>');
  <% end %>
<% else %>
  $('<%= "#question-#{ @question.id }" %>').replaceWith('<%= j render "question", question: @question %>');
<% end %>