config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  concern :likable do
    member do
      post :like_up
      post :like_down
      post :like_cancel
    end
  end

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  resources :questions, concerns: :likable do
    resources :comments, only: :create, defaults: { commentable: 'questions' }
    resources :answers, concerns: :likable, shallow: true do #only: [:new, :create, :destroy]
      resources :comments, only: :create, defaults: { commentable: 'answers' }
      member do
        patch 'mark_best'
      end
    end
    resources :subscriptions, only: [:create, :destroy], shallow:  true
  end

  namespace :api do
    namespace :v1 do
      resource :profiles do
        get :me, on: :collection
        get :users, on: :collection
      end
      resources :questions, only: [:index, :show, :create]
      resources :answers, only: [:index, :show, :create]
    end
  end

  get "oauth/new_email_for_oauth", as: 'new_email_for_oauth'
  post "oauth/save_email_for_oauth", as: 'save_email_for_oauth'

  get 'search', to: 'search#index'

  root to: "questions#index"
  resources :attachments, only: :destroy

end

app/models/search.rb
class Search < ActiveRecord::Base
  TYPES = %w(all questions answers comments users).freeze

  def self.find(request, type)
    query = Riddle::Query.escape(request)

    if type == 'all'
      ThinkingSphinx.search query
    else
      model = type.singularize.classify.constantize
      model.search query
    end
  end
end

app/controllers/search_controller.rb
# class SearchController < ApplicationController
#   def index
#     @search_results = Search.find(params[:search_request])
#   end
# end
class SearchController < ApplicationController
  skip_before_action :authenticate_user!
  before_action      :load_results

  authorize_resource class: false

  def index
    respond_with @search_results
  end

  private

  def load_results
    @search_results = Search.find(params[:search_request], params[:search_type])
  end
end

app/views/search/_answer.html.slim
h3 Answer
h4 = link_to record.body, question_path(record.question)

app/views/search/_comment.html.slim
h3 Comment
h4 = link_to record.body, question_path(record.commentable_id)

app/views/search/_form.html.slim
= form_tag search_path, method: "get" do
  = label_tag :search_request, "Search for:"
  = text_field_tag :search_request
  = select_tag 'search_type', options_for_select(Search::TYPES, params[:search_type])
  = submit_tag("Find")

app/views/search/_question.html.slim
h3 Question
h4 = link_to record.title, question_path(record)

app/views/search/_user.html.slim
h3 User
h4 = record.email

app/views/search/index.html.slim
- if @search_results.empty?
  h1 There is nothing to think
- else
  - @search_results.each do |record|
    p -
    = render "search/#{record.class.name.underscore}", record: record